# Credit to https://github.com/gaelgthomas/docker-compose-with-postgresql/blob/main/docker-compose.yml
version: "3"

services:
  postgres:
    image: "postgres:13.5-alpine"
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratemystocks

    volumes:
      - ./postgresql_database_data/:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    container_name: redis
    image: redis:6.2.3-alpine
    ports:
        - 6379:6379

volumes:
  postgresql_database_data:
